changelog:
  exclude:
    labels:
      - bot
    authors:
      - renovate
  categories:
    - title: 🪄 Funcionalidades e 🐛 correcoes
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
          - github_actions
          - housekeeping
    - title: 🧹 Manutencao
      labels:
        - housekeeping
    - title: 🧑‍💻 Dependencias
      labels:
        - dependencies
